import type { Destination } from './types';

export const DESTINATIONS: Destination[] = [
  {
    name: 'Hunza Valley',
    slug: 'hunza-valley',
    region: 'Gilgit-Baltistan',
    desc: "Turquoise lakes, ancient forts, and Karakoram peaks. Pakistan's most beloved valley.",
    best: 'Apr–Oct',
    image: 'https://picsum.photos/seed/hunza-full/1200/800',
    tags: ['Scenic', 'Trekking', 'Culture'],
  },
  {
    name: 'Lahore',
    slug: 'lahore',
    region: 'Punjab',
    desc: 'Mughal monuments, world-class food, and the beating cultural heart of Pakistan.',
    best: 'Oct–Mar',
    image: 'https://picsum.photos/seed/lahore-full/1200/800',
    tags: ['History', 'Food', 'Culture'],
  },
  {
    name: 'Skardu',
    slug: 'skardu',
    region: 'Gilgit-Baltistan',
    desc: 'Gateway to K2 and the Karakoram. Cold deserts, emerald lakes, and ancient rock carvings.',
    best: 'May–Sep',
    image: 'https://picsum.photos/seed/skardu-full/1200/800',
    tags: ['Adventure', 'Trekking', 'Scenic'],
  },
  {
    name: 'Swat Valley',
    slug: 'swat-valley',
    region: 'KPK',
    desc: 'Called the "Switzerland of the East" — lush green valleys, waterfalls and Buddhist ruins.',
    best: 'Apr–Oct',
    image: 'https://picsum.photos/seed/swat-full/1200/800',
    tags: ['Nature', 'History', 'Scenic'],
  },
  {
    name: 'Karachi',
    slug: 'karachi',
    region: 'Sindh',
    desc: "The city of lights. Pakistan's largest city with incredible seafood and street food culture.",
    best: 'Nov–Feb',
    image: 'https://picsum.photos/seed/karachi-full/1200/800',
    tags: ['Food', 'Beach', 'Urban'],
  },
  {
    name: 'Peshawar',
    slug: 'peshawar',
    region: 'KPK',
    desc: "One of the world's oldest cities. Ancient bazaars, Pashtun culture, and the Khyber Pass.",
    best: 'Oct–Mar',
    image: 'https://picsum.photos/seed/peshawar-full/1200/800',
    tags: ['History', 'Culture', 'Food'],
  },
  {
    name: 'Fairy Meadows',
    slug: 'fairy-meadows',
    region: 'Gilgit-Baltistan',
    desc: 'Alpine meadow at 3,300m with Nanga Parbat as its dramatic backdrop.',
    best: 'Jun–Sep',
    image: 'https://picsum.photos/seed/fairy-full/1200/800',
    tags: ['Adventure', 'Scenic', 'Trekking'],
  },
  {
    name: 'Mohenjo-daro',
    slug: 'mohenjo-daro',
    region: 'Sindh',
    desc: 'Walk through a 5,000-year-old UNESCO World Heritage city of the Indus Civilization.',
    best: 'Oct–Feb',
    image: 'https://picsum.photos/seed/mohenjo-full/1200/800',
    tags: ['History', 'UNESCO', 'Culture'],
  },
  {
    name: 'Deosai Plains',
    slug: 'deosai-plains',
    region: 'Gilgit-Baltistan',
    desc: "World's second-highest plateau. Vast wildflower meadows, Himalayan bears, and crystal streams.",
    best: 'Jul–Sep',
    image: 'https://picsum.photos/seed/deosai-full/1200/800',
    tags: ['Wildlife', 'Nature', 'Adventure'],
  },
  {
    name: 'Naran & Kaghan',
    slug: 'naran-kaghan',
    region: 'KPK',
    desc: 'The Kaghan Valley with Saiful Maluk lake and Babusar Pass is a summer paradise.',
    best: 'May–Sep',
    image: 'https://picsum.photos/seed/naran-full/1200/800',
    tags: ['Scenic', 'Lakes', 'Trekking'],
  },
  {
    name: 'Islamabad',
    slug: 'islamabad',
    region: 'Federal Capital',
    desc: "Pakistan's clean, green capital with the Margalla Hills, Faisal Mosque, and great food.",
    best: 'All Year',
    image: 'https://picsum.photos/seed/islamabad-full/1200/800',
    tags: ['Urban', 'Nature', 'Culture'],
  },
  {
    name: 'Makran Coast',
    slug: 'makran-coast',
    region: 'Balochistan',
    desc: 'Wild, dramatic coastline with golden beaches, hot springs, and the Princess of Hope rock.',
    best: 'Nov–Mar',
    image: 'https://picsum.photos/seed/makran-full/1200/800',
    tags: ['Beach', 'Adventure', 'Scenic'],
  },
];
