import type { Destination } from './types';

// Static fallback — no longer used by pages (they fetch from Supabase)
// Kept here to avoid breaking any imports elsewhere
export const DESTINATIONS: Destination[] = [
  {
    id: 'static-1',
    name: 'Hunza Valley',
    slug: 'hunza-valley',
    region: 'Gilgit-Baltistan',
    description: "Turquoise lakes, ancient forts, and Karakoram peaks. Pakistan's most beloved valley.",
    best_time: 'Apr–Oct',
    image_url: '/images/placeholder.jpg',
    tags: ['Scenic', 'Trekking', 'Culture'],
    published: true,
    sort_order: 1,
  },
  {
    id: 'static-2',
    name: 'Lahore',
    slug: 'lahore',
    region: 'Punjab',
    description: 'Mughal monuments, world-class food, and the beating cultural heart of Pakistan.',
    best_time: 'Oct–Mar',
    image_url: '/images/placeholder.jpg',
    tags: ['History', 'Food', 'Culture'],
    published: true,
    sort_order: 2,
  },
  {
    id: 'static-3',
    name: 'Skardu',
    slug: 'skardu',
    region: 'Gilgit-Baltistan',
    description: 'Gateway to K2 and the Karakoram. Cold deserts, emerald lakes, and ancient rock carvings.',
    best_time: 'May–Sep',
    image_url: '/images/placeholder.jpg',
    tags: ['Adventure', 'Trekking', 'Scenic'],
    published: true,
    sort_order: 3,
  },
  {
    id: 'static-4',
    name: 'Swat Valley',
    slug: 'swat-valley',
    region: 'KPK',
    description: 'Called the "Switzerland of the East" - lush green valleys, waterfalls and Buddhist ruins.',
    best_time: 'Apr–Oct',
    image_url: '/images/placeholder.jpg',
    tags: ['Nature', 'History', 'Scenic'],
    published: true,
    sort_order: 4,
  },
  {
    id: 'static-5',
    name: 'Karachi',
    slug: 'karachi',
    region: 'Sindh',
    description: "The city of lights. Pakistan's largest city with incredible seafood and street food culture.",
    best_time: 'Nov–Feb',
    image_url: '/images/placeholder.jpg',
    tags: ['Food', 'Beach', 'Urban'],
    published: true,
    sort_order: 5,
  },
  {
    id: 'static-6',
    name: 'Peshawar',
    slug: 'peshawar',
    region: 'KPK',
    description: "One of the world's oldest cities. Ancient bazaars, Pashtun culture, and the Khyber Pass.",
    best_time: 'Oct–Mar',
    image_url: '/images/placeholder.jpg',
    tags: ['History', 'Culture', 'Food'],
    published: true,
    sort_order: 6,
  },
  {
    id: 'static-7',
    name: 'Fairy Meadows',
    slug: 'fairy-meadows',
    region: 'Gilgit-Baltistan',
    description: 'Alpine meadow at 3,300m with Nanga Parbat as its dramatic backdrop.',
    best_time: 'Jun–Sep',
    image_url: '/images/placeholder.jpg',
    tags: ['Adventure', 'Scenic', 'Trekking'],
    published: true,
    sort_order: 7,
  },
  {
    id: 'static-8',
    name: 'Mohenjo-daro',
    slug: 'mohenjo-daro',
    region: 'Sindh',
    description: 'Walk through a 5,000-year-old UNESCO World Heritage city of the Indus Civilization.',
    best_time: 'Oct–Feb',
    image_url: '/images/placeholder.jpg',
    tags: ['History', 'UNESCO', 'Culture'],
    published: true,
    sort_order: 8,
  },
  {
    id: 'static-9',
    name: 'Deosai Plains',
    slug: 'deosai-plains',
    region: 'Gilgit-Baltistan',
    description: "World's second-highest plateau. Vast wildflower meadows, Himalayan bears, and crystal streams.",
    best_time: 'Jul–Sep',
    image_url: '/images/placeholder.jpg',
    tags: ['Wildlife', 'Nature', 'Adventure'],
    published: true,
    sort_order: 9,
  },
  {
    id: 'static-10',
    name: 'Naran & Kaghan',
    slug: 'naran-kaghan',
    region: 'KPK',
    description: 'The Kaghan Valley with Saiful Maluk lake and Babusar Pass is a summer paradise.',
    best_time: 'May–Sep',
    image_url: '/images/placeholder.jpg',
    tags: ['Scenic', 'Lakes', 'Trekking'],
    published: true,
    sort_order: 10,
  },
  {
    id: 'static-11',
    name: 'Islamabad',
    slug: 'islamabad',
    region: 'Federal Capital',
    description: "Pakistan's clean, green capital with the Margalla Hills, Faisal Mosque, and great food.",
    best_time: 'All Year',
    image_url: '/images/placeholder.jpg',
    tags: ['Urban', 'Nature', 'Culture'],
    published: true,
    sort_order: 11,
  },
  {
    id: 'static-12',
    name: 'Makran Coast',
    slug: 'makran-coast',
    region: 'Balochistan',
    description: 'Wild, dramatic coastline with golden beaches, hot springs, and the Princess of Hope rock.',
    best_time: 'Nov–Mar',
    image_url: '/images/placeholder.jpg',
    tags: ['Beach', 'Adventure', 'Scenic'],
    published: true,
    sort_order: 12,
  },
];
